### ISSUE TITLE
Exception when dragging after ctrl+click on selected node

### ISSUE THREAD

**Issue by aoldershaw** [prmr/JetUML#293]
**Description**
With a single node selected, if you attempt to drag on that node while holding the ctrl button (which deselects a node), a `java.util.NoSuchElementException` is thrown in the "JavaFX Application Thread".

**Steps to reproduce**
1. Create new class diagram 
2. Create a class node
3. Select the class node
4. While holding the ctrl key, click on the class node and drag the mouse
5. Exception is thrown

**Configuration**
 - JetUML Release: 2.3
 - OS + version: Mac OS 10.13.4
 - Java version: `Java(TM) SE Runtime Environment (build 1.8.0_111-b14)`
 
**Additional information**
With assertions disabled, the following exception is thrown:

```
Exception in thread "JavaFX Application Thread" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at ca.mcgill.cs.jetuml.gui.SelectionModel.getSelectionBounds(SelectionModel.java:86)
	at ca.mcgill.cs.jetuml.gui.DiagramCanvasController.computePointToReveal(DiagramCanvasController.java:517)
	at ca.mcgill.cs.jetuml.gui.DiagramCanvasController.mouseDragged(DiagramCanvasController.java:494)
	at ca.mcgill.cs.jetuml.gui.DiagramCanvasController.lambda$new$2(DiagramCanvasController.java:89)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

The contract of `SelectionModel.getSelectionBounds` is broken (in particular, the assertion `assert lastSelected.isPresent()`)

**Comment by AllanWang** [comment]
A simple fix would be to check for `aSelectionModel.isEmpty();` within the if statement:

https://github.com/prmr/JetUML/blob/5019f6a4cff915a164fc3b61597aebe3d181201e/src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java#L492-L496

**Comment by prmr** [comment]
Thanks for reporting and for the suggested fix.
