### ISSUE TITLE
Opening second diagram crashes on Mac 

### ISSUE THREAD

**Issue by neilernst** [prmr/JetUML#300]
**Description**
With one diagram already open, doing File→Open does not work. Subsequent mouse over of menus shows a red rectangle, then the regular menu. 

**Steps to reproduce**
1. Open a diagram.
2. Click on '.File→Open..'
3. Choose a JetUML diagram

**Configuration**
 - JetUML Release: 2.3
 - OS + version: Mac 10.14.3
 - Java version 1.8.0_131
 
**NPE**
```
java.lang.NullPointerException
	at com.sun.javafx.sg.prism.NGCanvas$RenderBuf.validate(NGCanvas.java:213)
	at com.sun.javafx.sg.prism.NGCanvas.initCanvas(NGCanvas.java:640)
	at com.sun.javafx.sg.prism.NGCanvas.renderForcedContent(NGCanvas.java:624)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:332)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by neilernst** [comment]
Possible related: #280

**Comment by prmr** [comment]
We tried to reproduce on MacOS 10.14.5 and could not. @neilernst can you try again with an updated OS?

**Comment by neilernst** [comment]
It still happens on 10.14.5 for me. Same JDK version.

**Comment by WinterAlexander** [comment]
OpenJDK bug with exact same stack trace: https://bugs.openjdk.java.net/browse/JDK-8174077

@neilernst Are you on OpenJDK? Can you try with an oracle JDK?

**Comment by neilernst** [comment]
Sorry, tried with Oracle JDK 1.8.0_221 and it still throws the same bug.

**Comment by prmr** [comment]
@neilernst do any of these situations apply to you:
* [The only certified MacOS versions are x64](https://www.oracle.com/technetwork/java/javase/certconfig-2095354.html)
* 10.15 "Catalina" is not certified (see above)
* [You are using VMWare](https://bugs.openjdk.java.net/browse/JDK-8146952)

**Comment by neilernst** [comment]
I am using Catalina, so that applies, but not the other 2.

**Comment by prmr** [comment]
Now subsumed by #324
