### ISSUE TITLE
Installation Issues on Debian

### ISSUE THREAD

**Issue by NumberC** [prmr/JetUML#424]
**Description**
I am trying to install JetUML on my Debian machine, but it always gives me an error:
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
```

**Steps to reproduce**

1. Download "JetUML-3.1-amd64.deb" from releases
2. Unzip the .deb
3. Unzip data.tar.xz
4. Go into opt/jetuml/bin/
5. Run JetUML

**Screenshots**
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Unknown Source)
        at java.base/java.io.InputStreamReader.<init>(Unknown Source)
        at jetuml/ca.mcgill.cs.jetuml.gui.tips.TipLoader.loadTip(Unknown Source)
        at jetuml/ca.mcgill.cs.jetuml.gui.tips.TipDialog.createScene(Unknown Source)
        at jetuml/ca.mcgill.cs.jetuml.gui.tips.TipDialog.prepareStage(Unknown Source)
        at jetuml/ca.mcgill.cs.jetuml.gui.tips.TipDialog.show(Unknown Source)
        at jetuml/ca.mcgill.cs.jetuml.JetUML.start(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
        ... 1 more
Exception running application ca.mcgill.cs.jetuml.JetUML

```

**Configuration**
 - JetUML Release: 3.1
 - OS + version: Debian 10
 - Java version: OpenJDK 11.0.9

**Comment by prmr** [comment]
The packaged linux binaries are offered on an as-is basis at the moment as we don't have resources for Linux support. In the meantime I would try running the [thin jar](https://github.com/prmr/JetUML/blob/master/docs/install.md) if you can (in which case you will need Java 14).
