### ISSUE TITLE
Object Diagram Group Deletion Problem

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#88]
In an object diagram, select a node that has fields with object references. Delete it and undo. Everything is fine. Instead of selecting the single node, lasso-select the entire node and its field, then delete and paste.  The object don't reappear and this exception gets raised:

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:643)
	at java.util.ArrayList.add(ArrayList.java:455)
	at ca.mcgill.cs.stg.jetuml.graph.HierarchicalNode.addChild(HierarchicalNode.java:68)
	at ca.mcgill.cs.stg.jetuml.commands.AttachDetachChildCommand.add(AttachDetachChildCommand.java:96)
	at ca.mcgill.cs.stg.jetuml.commands.AttachDetachChildCommand.undo(AttachDetachChildCommand.java:50)
	at ca.mcgill.cs.stg.jetuml.commands.CompoundCommand.undo(CompoundCommand.java:51)
	at ca.mcgill.cs.stg.jetuml.commands.CompoundCommand.undo(CompoundCommand.java:51)
	at ca.mcgill.cs.stg.jetuml.framework.UndoManager.undoCommand(UndoManager.java:70)
	at ca.mcgill.cs.stg.jetuml.framework.GraphPanel.undo(GraphPanel.java:238)
	at ca.mcgill.cs.stg.jetuml.framework.EditorFrame$2.actionPerformed(EditorFrame.java:214)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2878)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:689)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:668)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2970)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2841)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by prmr** [comment]
This issue was fixed as part of the refactoring for #105
